#!/bin/bash -ex
install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

# install ldap-utils for username maps script
install ldap-utils

# remove session interactive only setting from mkhomedir pam config
CONF=/usr/share/pam-configs/mkhomedir
sed -i "/Session-Interactive-Only/d" $CONF

# remove the smbpasswd-migrate pam config
rm /usr/share/pam-configs/smbpasswd-migrate

pam-auth-update --package

# add ldap configurations to samba
CONF=/etc/samba/smb.conf
sed -i "s|passdb backend.*|passdb backend = ldapsam:ldap://127.0.0.1\n\n    ldap ssl = off\n    ldap user suffix = ou=Users\n    ldap machine suffix = ou=Hosts\n    ldap group suffix = ou=Groups\n    ldap idmap suffix = ou=Idmaps\n    ldap suffix = dc=example,dc=com\n    ldap admin dn = cn=samba,dc=example,dc=com\n\n    idmap backend = ldap:ldap://127.0.0.1\n    idmap uid = 15000-55000\n    idmap gid = 15000-55000\n    template shell = /bin/bash\n\n    username map script = /usr/local/bin/ldapmapuser.sh|" $CONF

# prevent samba from starting on system boot until LDAP settings are configured
update-rc.d -f samba remove
